[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/" }]
solc_version = "0.8.26"
evm_version = "cancun"
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


additional_compiler_profiles = [
    { name = "manager", via_ir = true, optimizer_runs = 30000 },
]

compilation_restrictions = [
    { paths = "lib/v4-periphery/src/PositionManager.sol", optimizer_runs = 30000 },
]
